### ISSUE TITLE
npm run devでエラー

### ISSUE THREAD

**Issue by YUUJIIE** [YUUJIIE/laravel_ec#5]
https://readouble.com/laravel/9.x/ja/starter-kits.html

Laravel Breezeを導入する過程の
`npm run dev`でエラーが出る

```
root@ff1f5ba55962:/data# npm run dev
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> @ dev /data
> vite

/data/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `vite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-09T09_15_19_251Z-debug.log
```

npmとnodeのバージョンが合ってない？

**Comment by YUUJIIE** [comment]
https://zenn.dev/404_notfound/articles/38e296b353c02e

Dockerfileでnodeのバージョン指定してインストールすれば解決？
```
&&  curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs \
```

**Comment by YUUJIIE** [comment]
Dockerfileに以下を追記して解決
```
curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs  && \
```
npm run devは解決したが、レイアウトが崩れる。
CSSが効いていない？
